### PR TITLE
Upgrade Castle Facility for Quartz v3.0.2

### PR DESCRIPTION
**Pull request by kristofdc**
Castle Facility for Quarts is now compatible with Quartz.Net v3

### CODE REVIEW

**Comment by jonorossi** [comment]
@kristofdc thanks for your pull request it looks great (except it has no description), however this project has no active maintainer which is why it lives in the "castleproject-deprecated" GitHub organisation.

It appears that the Quartz.NET project is more active than it was a few years ago and that you know your way around Quartz.NET. Are you interested in becoming the maintainer of this Windsor facility? That would basically mean you get to control what happens with this facility?

The Castle Project doesn't "own" the `Quartz.Windsor` package on NuGet.org as this project used to be a "contrib" project never an actual official facility, @mausch would you mind "castleproject" also being an owner?

**Comment by kristofdc** [comment]
@jonorossi I would like to be a maintainer, but I am missing some time to do. :-)

**Comment by jonorossi** [comment]
> I would like to be a maintainer, but I am missing some time to do. :-)

This project has been a ghost town for 4 years, it wouldn't be a big time commitment, at this stage you'd just be maintaining it for yourself.

**Comment by kristofdc** [comment]
Ok then, @jonorossi. In that case I can spent some time on it !

**Comment by jonorossi** [comment]
Changes look good, merging.

**Comment by jonorossi** [comment]
@kristofdc looks like the nuspec needs an update, but first things first I think this project needs an automated build.

**Comment by kristofdc** [comment]
How can I create automated build on GitHub? + how can we put the newest nuget package into the nuget store?

**Comment by jonorossi** [comment]
> How can I create automated build on GitHub?

We've been using AppVeyor for Windsor builds, see that repository. Feel free to create an AppVeyor account and set it up on your own fork to get it going, then send a pull request with a working appveyor.yml file.

With the Windsor build we've even gone to the level where it'll automatically publish the NuGet package to nuget.org when you tag a commit in Git. Your call on how far you want to go here, probably a good idea to start small though.

> how can we put the newest nuget package into the nuget store?

As I mentioned in a previous comment @mausch controls the `Quartz.Windsor` package on nuget.org, I've pinged him by email, will let you know when I get a response.

Feel free to create new issues for things that need to be done.

**Comment by kristofdc** [comment]
@jonorossi new pull request is waiting with support for .NET Standard 2.0 and appveyor build configuration

**Comment by mausch** [comment]
Sorry for the late reply. Glad to see new interest and activity around this project! I just gave ownership of the nuget package to Jono.

**Comment by jonorossi** [comment]
Thanks @mausch, we released 0.5.0 (#25) a week ago under the package name `Castle.Facilities.Quartz` also because it better reflects that this is a Castle project not a Quartz.NET project (i.e. the prefix).

Maybe we should unlist the versions of `Quartz.Windsor` but obviously keep the package available, I've done that with 2 obsolete Windsor packages in the past?

**Pull request merged**
